is-virtual = false
base16-scheme = "seti"
wireless = ["wlp5s0"]
ethernet = ["enp6s0"]
disks = ["/"]
# hwmon2 = k10temp, temp1 = Tctl
temperature-path = "/sys/class/hwmon/hwmon2/temp1_input"

outputs = [
    "\"ASUSTek COMPUTER INC VG258 M1LMQS004947\" position 0 0 mode 1920x1080@165Hz",
    "\"BNQ BenQ GL2580 46J02196SL0\" position 1920 0 mode 1920x1080@60Hz",
    "\"BNQ BenQ GL2580 46J02151SL0\" position 3840 0 mode 1920x1080@60Hz",
    "\"Pioneer Electronic Corporation AV Receiver Unknown\" mode 3840x2160@60Hz scale 2.0",
]
