wireless = ["wlp0s20f3"]
ethernet = ["eno1"]

[[outputs]]
match = "*"
background = ["~/.local/share/backgrounds/concord/full.jpg", "fill"]

[[outputs]]
match = "Pioneer Electronic Corporation AV Receiver Unknown"
mode = "3840x2160@60Hz"
scale = 2
