wireless = ["wlp170s0"]
#ethernet = ["enp2s0"]
temperature-path = "/sys/class/hwmon/hwmon4/temp1_input"

[[outputs]]
match = "eDP-1"
scale = 1.5
background = ["~/.local/share/backgrounds/sway-dark-1920x1080.png", "fill"]

[[inputs]]
match = "2362:628:PIXA3854:00_093A:0274_Touchpad"
tap = "enabled"
