ethernet = ["enp0s3"]
disks = ["/"]
outputs = [
    { name = "Virtual1", config = ["--auto", "--primary"] },
    { name = "Virtual2" },
    { name = "Virtual3" },
    { name = "Virtual4" },
    { name = "Virtual5" },
    { name = "Virtual6" },
    { name = "Virtual7" },
    { name = "Virtual8" },
]
