wireless = ["wlp36s0"]
ethernet = ["enp37s0"]
disks = ["/", "/home"]
outputs = [
    { name = "HDMI-A-0", config = ["--auto", "--primary"] },
    { name = "DVI-D-0", config = ["--auto", "--left-of", "HDMI-A-0"] },
    { name = "DisplayPort-0" },
]
