runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
filetype on
syntax on
set colorcolumn=90
set number
set hidden
set history=100
filetype indent on
set nowrap
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent
set autoindent
set hlsearch
set showmatch
set directory=$HOME/.vim/tmp
set backupdir=$HOME/.vim/tmp
